apiVersion: v1
kind: Pod
metadata:
  name: rating
spec:
  containers:
  - name: rating
    image: 767397836388.dkr.ecr.ap-southeast-1.amazonaws.com/docker-hub-a887/tunnyeinmua/bookinfo-ratings-v1:1.20.3
  imagePullSecrets:
  - name: regcred

